{
  "hash": "512b93330d10bab853ea423f8e1158b9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Homework 1: One Sample Inference\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\nHuman toddlers, starting at around 18 months old, can learn novel object labels passively by overhearing third-party\ninteractions without being directly addressed. For example, if one adult says “hand me an apple” and another does\nso, the child might learn to identify an apple and associate it with the word “apple”.\nThis process is driven by developing sociocognitive capacities such as gaze following, conversation monitoring, intention\nunderstanding, and perspective-taking. Of course, this process is more efficient when adults use simplified sentences,\nemphasis, enthusiasm, and other non-verbal emphasis.\nDogs share some human-like social and cognitive abilities they learn being immersed in our households. For example,\nmany family dogs learn actions like “sit.” Dror et al. (2026) explored whether dogs could be capable of passive label\nlearning, similar to toddlers. Specifically, they were interested in Gifted Word Learner (GWL) dogs that can learn\nthe names of hundreds of objects and perform at a word-learning level comparable to 18 months olds.\nTo learn whether GWL dogs learn object labels by passively overhearing interactions between humans the researchers\nperformed an experiment where 𝑛 = 10 dogs were exposed to a condition where two family members sitting across\nfrom each other passing the toy back and forth. The caretaker addressed the second person using simple sentence\nframes and non-verbal cues, neither directly to the dog.\nThis exposure occurred daily for eleven days with two new toys. \\\n• Toy A: Days 1-3; 9 \\\n• Toy B: Days 5-7; 10 \\\n• Rest: Day 4, 8, 11 \\\nOn the twelfth day, out of the caretaker’s sight, the two new toys were placed alongside nine familiar toys. The\ncaretaker requested the toys verbally twenty-four times – twelve times for the two new toys, and twelve times for the\nnine familiar toys.\n\n# Question 1\n## Part a\nThe researchers are asking two questions: (1) whether performance in the\noverhearing condition is above 50% chance, and (2) whether the\ndifference between the direct and overhearing conditions differs from zero.\n\nBefore choosing a test we summarize each data set.\n\n::: {.cell}\n\n```{.r .cell-code}\noverhear <- c(1.0000, 1.0000, 0.7500, 1.0000, 0.4167,\n              0.8333, 0.7500, 0.8333, 0.8333, 1.0000)\n\npdiff <- c(-0.0833, 0.0000, -0.0833, -0.0833, 0.5833,\n            0.0833, -0.2500,  0.1667, 0.0000, -0.4167)\n\nsummarize.data <- function(x){\n  tibble(\n    n                 = length(x),\n    Mean              = mean(x),\n    SD                = sd(x),\n    Median            = median(x),\n    IQR               = IQR(x),\n    Skewness          = e1071::skewness(x),\n    `Excess Kurtosis` = e1071::kurtosis(x),\n    Min               = min(x),\n    Max               = max(x)\n  )\n}\n```\n:::\n\n\n\n::: {#tbl-overhear .cell tbl-cap='Descriptive statistics for the overhearing condition'}\n\n```{.r .cell-code}\nsummarize.data(overhear) |> knitr::kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|  n| Mean|   SD| Median|  IQR| Skewness| Excess Kurtosis|  Min| Max|\n|--:|----:|----:|------:|----:|--------:|---------------:|----:|---:|\n| 10| 0.84| 0.18|   0.83| 0.23|    -1.04|            0.22| 0.42|   1|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = tibble(overhear), aes(x = overhear)) +\n  geom_histogram(aes(y = after_stat(density)),\n                 breaks = seq(0, 1, 0.1),\n                 color = \"grey\") +\n  geom_hline(yintercept = 0) +\n  theme_bw() +\n  labs(x = \"Proportion of Correct Retrievals Out of 12 Trials\",\n       y = \"Density\")\n```\n\n::: {.cell-output-display}\n![Proportion of correct retrievals in the overhearing condition](hw1_files/figure-html/fig-overhear-1.png){#fig-overhear width=672}\n:::\n:::\n\n\n\n::: {#tbl-pdiff .cell tbl-cap='Descriptive statistics for the paired differences'}\n\n```{.r .cell-code}\nsummarize.data(pdiff) |> knitr::kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|  n|  Mean|   SD| Median|  IQR| Skewness| Excess Kurtosis|   Min|  Max|\n|--:|-----:|----:|------:|----:|--------:|---------------:|-----:|----:|\n| 10| -0.01| 0.26|  -0.04| 0.15|      0.7|            0.15| -0.42| 0.58|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = tibble(pdiff), aes(x = pdiff)) +\n  geom_histogram(aes(y = after_stat(density)),\n                 breaks = seq(-0.5, 0.7, 0.1),\n                 color = \"grey\") +\n  geom_hline(yintercept = 0) +\n  theme_bw() +\n  labs(x = \"Difference in Proportion (Direct − Overhearing)\",\n       y = \"Density\")\n```\n\n::: {.cell-output-display}\n![Paired differences (direct − overhearing)](hw1_files/figure-html/fig-pdiff-1.png){#fig-pdiff width=672}\n:::\n:::\n\n\n### The overhearing data\n\nWe cannot use the $t$-test because the distribution is left skewed and bounded, and the sample size is too small to invoke the Central Limit Theorem.\n\nWe cannot use the exact Wilcoxon test because there are ties and the distribution is skewed. We also cannot use the approximate Wilcoxon test because the sample size is less than $50$. So, the authors did not make a good choice in selecting Wilcoxon test and without specifying exact or approximate. \n\nWe cannot use the $z$-test because $np_0 = 10(0.50) = 5$, below the\nrequired 15.\n\nI would use the exact Binomial test, which involves transforming the data into Bernoulli data (i.e., whether each dog retrieved the correct new toys in more than half of the 12 trials). \n\n### The paired differences data\n\nWe cannot use the $t$-test because the distribution is skewed and the sample size is too small for the Central Limit Theorem. \n\nWe cannot use the Wilcoxon test because there are zeros and ties, and the overall distribution is not symmetric. \n\nWe cannot use the exact Binomial test here because we are interested in how large the difference between conditions is, and reducing the data to signs treats a difference of 0.0833 and a difference of 0.5833 the same, losing important information.\n\nI would use a randomization test. This uses the actual magnitudes rather than just the signs, and makes no assumption about the shape of the population distribution.\n\n## Part b\nWe want to know whether the dogs retrieved the new toys above 50% chance, and whether there is a difference between the two conditions: direct address and overhearing. \n\n### Research Question 1: Is performance above chance?\nTransform the data into Bernoulli form, recording whether each dog\nretrieved the new toys correctly on more than half of its twelve trials, and use the exact Binomial test. \n\n**Conditions.** The variable is categorical after transformation. The dogs come from separate households, so observations are independent across dogs. The sample is a good representation of the Gifted Word Learner dogs. The exact Binomial test imposes no condition on sample size.\n\n- $H_0$: $p = 0.50$ \\\n- $H_a$: $p \\neq 0.50$ \\\n\n\n::: {.cell}\n\n```{.r .cell-code}\noverhear.bernoulli <- as.numeric(overhear > 0.50)\n\nrq1.result <- binom.test(x = sum(overhear.bernoulli),\n                         n = length(overhear.bernoulli),\n                         p = 0.50,\n                         alternative = \"two.sided\",\n                         conf.level = 0.95)\n\nrq1.result$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02148438\n```\n\n\n:::\n\n```{.r .cell-code}\nrq1.result$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5549839 0.9974714\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n\n```{.r .cell-code}\n(cohens.h <- 2*asin(sqrt(0.9)) - 2*asin(sqrt(0.5)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9272952\n```\n\n\n:::\n:::\n\n\nOf the ten dogs tested, nine performed above chance across their twelve\ntrials. This proportion was statistically discernible from the chance level of $0.5$, $p = .021$, 95% CI $[.555, .997]$. The effect size was large, Cohen's $h = 0.927$.\n\nThere is statistically discernible support for the alternative hypothesis. The dogs retrieved the new toys above chance in the overhearing condition, which indicates that they can associate labels with objects from overheard speech alone. The interval, .555 to .997, is wide. The dogs clearly did better than chance, but with only ten of them we cannot tell whether they are a little better or almost perfect.\n\n### Research Question 2: Do the two conditions differ?\nUse a randomization test, which uses the observed magnitudes and makes no assumption about the shape of the population distribution.\n\n**Conditions.** The variable is quantitative. The dogs are independent of one another. Under the null hypothesis the two conditions are interchangeable within a dog, so we can flip the sign,\n\n- $H_0$: $\\mu_X = 0$ \\\n- $H_a$: $\\mu_X \\neq 0$ \\\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7272)\nR <- 10000\n\nnull.dist <- rep(NA, R)\nfor(i in 1:R){\n  signs <- sample(x = c(-1, 1), size = length(pdiff), replace = TRUE)\n  null.dist[i] <- mean(signs * pdiff)\n}\n\n(observed <- mean(pdiff))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.00833\n```\n\n\n:::\n\n```{.r .cell-code}\n(rq2.pvalue <- mean(abs(null.dist) >= abs(observed)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9847\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = tibble(null.dist), aes(x = null.dist)) +\n  geom_histogram(aes(y = after_stat(density)),\n                 bins = 30, color = \"grey\") +\n  geom_vline(xintercept = observed, linetype = \"dashed\") +\n  geom_hline(yintercept = 0) +\n  theme_bw() +\n  labs(x = \"Mean Paired Difference Under the Null\",\n       y = \"Density\")\n```\n\n::: {.cell-output-display}\n![Null distribution of the mean paired difference, with the observed value marked](hw1_files/figure-html/fig-null-1.png){#fig-null width=672}\n:::\n:::\n\n\nA confidence interval for the mean difference is obtained by bootstrapping.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7272)\nboot.means <- rep(NA, R)\nfor(i in 1:R){\n  curr.sample <- sample(x = pdiff, size = length(pdiff), replace = TRUE)\n  boot.means[i] <- mean(curr.sample)\n}\n\n(rq2.ci <- quantile(boot.means, probs = c(0.025, 0.975)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    2.5%    97.5% \n-0.15001  0.15833 \n```\n\n\n:::\n\n```{.r .cell-code}\n(hedges.g <- effectsize::hedges_g(x = pdiff, mu = 0))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHedges' g |        95% CI\n-------------------------\n-0.03     | [-0.59, 0.54]\n```\n\n\n:::\n:::\n\n\nThe mean paired difference observed in our sample was not statistically\ndiscernible from zero, $M = -0.008$, $SD = 0.265$, $p = .99$, 95% CI\n$[-0.15, 0.16]$. The effect size was negligible, Hedges' $g = -0.03$.\n\nWe do not have statistically discernible support for the alternative hypothesis. The dogs did about as well whether the caretaker spoke to them directly or they only overheard the labels. The first result showed that overhearing beats chance; this second one shows it is not worse than being taught directly. Taken together, overhearing is sufficient for the dogs to learn labels. \n\n# Question 2\nThe researchers evaluated two new-toy trials per dog across 𝑛 = 10 dogs. In the overheard condition, the dogs\nretrieved all the new toys correctly on the first try. That is, the proportion of times the dogs retrieved the new toys\nthey had only learned through overhearing was 1.0.\n## Part a\nThe binomial model is a sum of Bernoulli trials. Thus, each $X_i$ must have a binary outcome, the number of trials $n$ must be fixed, the trials must be independent, and the probability of the event of interest $p$ must be the same in every trial. \n\nFirst, retrieval is binary: the dog either brings the requested toy or it does not. Second, the design fixed $n = 10$ dogs with two trials each, so $n$ was fixed. Third, I think the trails are not independent. A dog that learned the label should succeed on both trials, and a dog that did not should tend to fail on both. So the two outsomes seems to be linked in someways rahter than fully independent. Finally, I doubt the probability stays the same in every trial. Once the first toy has been retrieved, the total number of toy decrease by one. So next time, the dog is selecting among 10 toys. The probability will change.  \n\n## Part b\nUnder author assumption that a single retrieval succeeds by chance with\nprobability $0.5$, and two retrievals are independent,\n$$P(X_i = 1) = 0.5 \\times 0.5 = 0.25.$$\n$$B = \\sum_{i=1}^{10} X_i \\sim \\text{Binomial}(n = 10,\\ p = 0.25),$$\n\n::: {.cell}\n\n```{.r .cell-code}\ndbinom(x = 10, size = 10, prob = 0.25)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.536743e-07\n```\n\n\n:::\n:::\n\n\n## Part c\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 10\np <- 0.25\nmu <- n * p\nsigma <- sqrt(n * p * (1 - p))\n\napprox <- pnorm(q = 10.5, mean = mu, sd = sigma) -\n          pnorm(q = 9.5,  mean = mu, sd = sigma)\nexact  <- dbinom(x = 10, size = 10, prob = 0.25)\n\nc(exact = exact, approx = approx, ratio = exact / approx)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       exact       approx        ratio \n9.536743e-07 1.567447e-07 6.084254e+00 \n```\n\n\n:::\n:::\n\n\nThe approximation is $1.567 \\times 10^{-7}$, and the exact value from Part b is $9.537 \\times 10^{-7}$. For abs error, they differ by about $8 \\times 10^{-7}$, which is pretty small. While for rel error, the approximation is poor. The approximation understates the true value by roughly 84%. \n\n## Part d\nWhen all trials are successes, $\\hat{p} = 1$ and the standard error\n$\\sqrt{\\hat{p}(1-\\hat{p})/n}$ becomes zero, so the $z$ interval collapses to the\nsingle point $[1, 1]$. The sample size condition fails too, since\n$n(1-\\hat{p}) = 0$. When these conditions are not met we\ncan use the exact Binomial distribution. \\\n$$H_0: p = 0.25 \\qquad H_a: p > 0.25$$\n\n::: {.cell}\n\n```{.r .cell-code}\ntest.result = binom.test(x = 10,  \n                         n = 10,  \n                         p = 0.25, \n                         alternative = \"greater\",\n                         conf.level = 0.95)\ntest.result$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.536743e-07\n```\n\n\n:::\n\n```{.r .cell-code}\ntest.result$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7411344 1.0000000\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\nThere is statistically discernible support for the alternative hypothesis: the dogs performed better than chance.\n\n# References\nDror, Shany, Ádám Miklósi, Boglárka Morvai, Andreea-Silvia Năstase, and Claudia\nFugazza. 2026. \"Dogs with a Large Vocabulary of Object Labels Learn New Labels\nby Overhearing Like 1.5-Year-Old Infants.\" *Science* 391 (6781): 160–63.\n",
    "supporting": [
      "hw1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}