{
  "hash": "a334d4f78f1045551fd7be3ca988d2e6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Homework 2 -- k Sample Inference # Title of the document\n\n# Bibliography Details\nbibliography: HW2References.bib  # Name of bib file in the same folder \nbibliographystyle: apa            # Bibliography style\n\nexecute:               # Default settings for code blocks\n  warning: false       # Do not print warnings\n  message: false       # Do not print messages\n  size: \"scriptsize\"   # Set code size to script size\n\n# Below will do html by default. To render the entire project\n# Use the following code:\n# quarto::quarto_render(\"Lab10WriteUp.qmd\")\nformat:\n  pdf:        # Specify .pdf formatting options \n    documentclass: article     # Document Class\n    number-sections: true      # Number Sections\n    reference-section-title: \"References\" # Title for reference section\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables \n    geometry:\n      - top=0.75in\n      - left=0.75in\n      - bottom=0.75in\n      - right=0.75in\n  html:       # Specify HTML formatting options \n    number-sections: true      # Number Sections\n    code-fold: true            # Button to show code\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables and figures\nformat-links: [pdf]\n---\n\n \\normalsize\n\n\n::: {.cell}\n\n:::\n\n\n \\normalsize\n\n\n\n# Question 1: Why do we Correct for Multiple Comparisons?\nA student asked me what the point of correcting for multiple comparisons was. They made a two interesting points:\n\n1. They are different outcomes, so, unlike the coin flip example (where the coin is the same) it doesn't makes sense to combine them.\n2. If a manuscript presented three studies with $t$-tests, they don't correct for multiple comparisons across *those* tests.\n\nWhen we conduct all pairwise comparisons after an omnibus test like ANOVA, we are testing a single family of hypotheses to answer one overarching question (\"Which of these groups are different?\"). Every additional test provides another opportunity to commit a Type I error from random noise. Similar to the coin, the probability of making at least one false error across $J$ independent tests grows exponentially: $1 - (1 - \\alpha)^J$. Note that our pairwise comparisons are not independent, so it's slightly different.\n\nWe don't correct for inferences across separate studies because they typically test distinct hypotheses using independent samples. Our attempt to address the multiple comparisons problem is specifically confined to the issue of increased Type I error within a single decision-making context. If we don't, we can find ourselves in a $p$-hacking-like situation, where an investigator might search through many tests to find one $p < 0.05$ (a potential false discovery), rather than making decisions to best position themselves for finding a true discovery.\n\nHere, we will quickly demonstrate why we correct for the multiple comparisons problem when conducting several tests to answer the same question. \n\n## Part a\nComplete the following steps in $R=1000$ simulations.\n\n1. Simulate data for $k=5$ samples $n=30$ drawn from a standard Gaussian distribution.\n2. Use `pairwise.t.test(..., p.adjust.method=\"none\")` to compute unadjusted pairwise $t$-tests and record if any comparison yields statistically discernible support for a non-zero mean.\n3. Use `rstatix::tukey_hsd(...)` to compute the Tukey's HSD adjusted pairwise tests and record if any comparison yields statistically discernible support for a non-zero mean.\n\nIn the end, describe the Type I error rates.\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(354)\n\nR <- 1000           \nk <- 5              \nn <- 30             \nalpha <- 0.05\n\nreject.none  <- rep(NA, R)\nreject.tukey <- rep(NA, R)\n\nfor(r in 1:R){\n  dat <- tibble(Group    = factor(rep(paste(\"Group\", 1:k), each = n)),\n                Response = rnorm(k * n, mean = 0, sd = 1))\n  \n  pairwise.result <- pairwise.t.test(dat$Response, dat$Group, \n                                     p.adjust.method = \"none\")\n  reject.none[r] <- any(pairwise.result$p.value < alpha, na.rm = TRUE)\n  \n  test.result    <- aov(Response ~ Group, data=dat)\n  posthoc.result <- tukey_hsd(test.result)\n  reject.tukey[r] <- any(posthoc.result$p.adj < alpha)\n}\n\n(results <- tibble(Method = c(\"Unadjusted t-tests\", \"Tukey's HSD\"),\n                   FWER   = c(mean(reject.none), mean(reject.tukey))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  Method              FWER\n  <chr>              <dbl>\n1 Unadjusted t-tests 0.294\n2 Tukey's HSD        0.053\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nWithout adjustment, the Type I error rate across the ten pairwise comparisons was 0.294, way larger than $\\alpha = 0.05$. With Tukey's HSD, it was 0.053, very close to $\\alpha = 0.05$. Tukey's HSD keeps the family-wise Type I error rate at $\\alpha$; unadjusted $t$-tests do not.\n\n## Part b\nRedo the simulation, changing to adjust according to the false discovery rate `p.adjust.method=\"BH\"` and comment on the differences.\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(354)\n\nreject.BH      <- rep(NA, R)\nreject.tukey.b <- rep(NA, R)\n\nfor(r in 1:R){\n  dat <- tibble(Group    = factor(rep(paste(\"Group\", 1:k), each = n)),\n                Response = rnorm(k * n, mean = 0, sd = 1))\n  \n  pairwise.result <- pairwise.t.test(dat$Response, dat$Group, \n                                     p.adjust.method = \"BH\")\n  reject.BH[r] <- any(pairwise.result$p.value < alpha, na.rm = TRUE)\n  \n  test.result    <- aov(Response ~ Group, data=dat)\n  posthoc.result <- tukey_hsd(test.result)\n  reject.tukey.b[r] <- any(posthoc.result$p.adj < alpha)\n}\n\n(results.b <- tibble(Method = c(\"Unadjusted t-tests\", \"BH (FDR)\", \"Tukey's HSD\"),\n                     FWER   = c(mean(reject.none), mean(reject.BH), \n                                mean(reject.tukey.b))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  Method              FWER\n  <chr>              <dbl>\n1 Unadjusted t-tests 0.294\n2 BH (FDR)           0.047\n3 Tukey's HSD        0.053\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nWith the Benjamini-Hochberg adjustment, the Type I error rate was 0.047, close to $\\alpha = 0.05$ and similar to Tukey's HSD (0.053). This is because every null hypothesis is true in this simulation, so any rejection is a false discovery and the false discovery rate equals the family-wise error rate. \n\n# Question 2: Power Analyses\nRevisit the MFAP4 study from class. \n\n## Part a\nAssume the researchers were targeting a moderate effect size of Cohen's $f = 0.25$, setting significance level $\\alpha = 0.05$ and desired power $1 - \\beta = 0.80$. Were they adequately powered?\n\n**Note**: The actual effect size is $f=0.55$, but researchers usually do not know that ahead of time and defaulted to moderate, instead of specifying a large effect.\n\nWhat is the required sample size per group ($n$) and the overall total sample size ($N$)? Write the `R` code using the `pwr` package to calculate this sample size. This package assumes all samples are of the same size so $N=nk$, where $k$ is the number of samples. Note that the best answers will have a corresponding graphical display.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk.2   <- 5        \nf.2   <- 0.25    \nalpha <- 0.05\n\n(n.a <- ceiling(pwr.anova.test(k = k.2,\n                               f = f.2,\n                               sig.level = alpha,\n                               power = 0.80)$n))  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 40\n```\n\n\n:::\n\n```{.r .cell-code}\n(N.a <- n.a * k.2)                                  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 200\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nTo detect a moderate effect ($f = 0.25$) with $\\alpha = 0.05$ and 80% power across $k = 5$ groups, the researchers need $n = 40$ patients per group, or $N = 200$ in total. The study was adequately powered: every fibrosis stage had more than 40 patients and the total sample of $N = 542$ is well above 200.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf1    <- k.2 - 1\ndf2    <- N.a - k.2\nlambda <- k.2 * n.a * f.2^2\nF.crit <- qf(1 - alpha, df1, df2)\npower.a <- 1 - pf(F.crit, df1, df2, ncp = lambda)\n\nplot.dat <- tibble(x = seq(0, 15, length.out = 1000)) |>\n  mutate(null = df(x, df1, df2),\n         alt  = df(x, df1, df2, ncp = lambda))\n\nggplot(plot.dat, aes(x = x)) +\n  geom_area(data = filter(plot.dat, x >= F.crit), \n            aes(y = alt, fill = \"Power\"), alpha = 0.6) +\n  geom_area(data = filter(plot.dat, x <= F.crit), \n            aes(y = alt, fill = \"Type II Error\"), alpha = 0.6) +\n  geom_area(data = filter(plot.dat, x >= F.crit), \n            aes(y = null, fill = \"Type I Error\"), alpha = 0.6) +\n  geom_line(aes(y = null, color = \"Null Distribution\")) +\n  geom_line(aes(y = alt,  color = \"Alternative Distribution\")) +\n  geom_hline(yintercept = 0) +\n  scale_fill_manual(\"\", values = c(\"Power\" = \"goldenrod\", \n                                   \"Type I Error\" = \"darkred\", \n                                   \"Type II Error\" = \"grey70\")) +\n  scale_color_manual(\"\", values = c(\"Alternative Distribution\" = \"black\",\n                                    \"Null Distribution\" = \"darkred\")) +\n  theme_bw() +\n  labs(x = \"F\", y = \"Density\",\n       title = paste0(\"f = 0.25, k = 5, n = \", n.a, \" per group (N = \", N.a, \")\"))\n```\n\n::: {.cell-output-display}\n![](HW2_files/figure-html/q2a-plot-1.png){width=672}\n:::\n:::\n\n\n \\normalsize\n\n## Part b\nThe project was funded by several agencies. Suppose that a funding agency suggested funding limiting the researchers to $N=150$. Evaluate this suggestion in the context of the ANOVA. Would that be large enough to be adequately powered?\n\nCompute the non-centrality parameter \n$$\\lambda = k \\cdot n \\cdot f^2$$\nand use the non-central $F$ distribution to compute the power under $H_a$ for Cohen's $f = 0.25$.  Calculate the statistical power achieved under this budget constraint. Note that the best answers will have a corresponding graphical display.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nN.b <- 150\nn.b <- N.b / k.2                        \n\ndf1.b    <- k.2 - 1                     \ndf2.b    <- N.b - k.2                   \nlambda.b <- k.2 * n.b * f.2^2           \nF.crit.b <- qf(1 - alpha, df1.b, df2.b) \npower.b  <- 1 - pf(F.crit.b, df1.b, df2.b, ncp = lambda.b)  \n\nlambda.b\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.375\n```\n\n\n:::\n\n```{.r .cell-code}\npower.b\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6675964\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot.dat.b <- tibble(x = seq(0, 15, length.out = 1000)) |>\n  mutate(null = df(x, df1.b, df2.b),\n         alt  = df(x, df1.b, df2.b, ncp = lambda.b))\n\nggplot(plot.dat.b, aes(x = x)) +\n  geom_area(data = filter(plot.dat.b, x >= F.crit.b), \n            aes(y = alt, fill = \"Power\"), alpha = 0.6) +\n  geom_area(data = filter(plot.dat.b, x <= F.crit.b), \n            aes(y = alt, fill = \"Type II Error\"), alpha = 0.6) +\n  geom_area(data = filter(plot.dat.b, x >= F.crit.b), \n            aes(y = null, fill = \"Type I Error\"), alpha = 0.6) +\n  geom_line(aes(y = null, color = \"Null Distribution\")) +\n  geom_line(aes(y = alt,  color = \"Alternative Distribution\")) +\n  geom_hline(yintercept = 0) +\n  scale_fill_manual(\"\", values = c(\"Power\" = \"goldenrod\", \n                                   \"Type I Error\" = \"darkred\", \n                                   \"Type II Error\" = \"grey70\")) +\n  scale_color_manual(\"\", values = c(\"Alternative Distribution\" = \"black\",\n                                    \"Null Distribution\" = \"darkred\")) +\n  theme_bw() +\n  labs(x = \"F\", y = \"Density\",\n       title = paste0(\"f = 0.25, k = 5, n = \", n.b, \" per group (N = \", N.b, \")\"))\n```\n\n::: {.cell-output-display}\n![](HW2_files/figure-html/q2b-plot-1.png){width=672}\n:::\n:::\n\n\n \\normalsize\n\nWith $N = 150$, each group has $n = 30$ patients, which is below the $n = 40$ required in Part a. The non-centrality parameter is 9.375, and the power is 0.668. The study is underpowered to detect a moderate effect.\n\n## Part c\nIn the article the researchers state:\n\n> *However, the statistical power was not sufficient to allow an accurate discrimination of no to moderate stages of hepatic fibrosis (F0–F2) from severe fibrosis and cirrhosis (F3 and F4).*\n\nThe European Association for the Study of the Liver (EASL) provides treatment recommendations based on these stages. \n\n* Stages 0-1: Treatment is deferred with regularly assessment\n* Stage 2: Treatment is justified for those in stage 2\n* Stage 3-4: Treatment is a priority for those in stages\n\nSuppose the researcher wanted to perform a follow-up test where they want to ensure adequate power not just for the overall ANOVA $F$-test, but specifically to detect a pairwise differences between stages 1 and 2. Explain why the sample size computed in Part a may not be enough and use `PMCMRplus::power.tukey.test()` to compute a sample size that attains adequate power. \n\n**Note**: The researchers would have had to do this *a priori*. Because we aren't medical experts, you can use sample estimates using the original data.\n\\begin{align*}\n  n & = \\text{answer from part a}\\\\\n  \\mu_{\\Delta} & = 0.25 \\\\ \n  \\sigma^2_{\\text{pooled}} & = \\frac{(176-1)0.85^2 + (135-1)0.84^2}{176+135-2} = 0.7152\\\\\n  \\sigma_{\\text{within}}= 0.77\n\\end{align*}\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndelta.c <- 0.25    \nvar.c   <- 0.77     \n\npower.c.a <- PMCMRplus::power.tukey.test(n = n.a, groups = k.2, \n                                         delta = delta.c, \n                                         within.var = var.c)$power\npower.c.a\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.07194129\n```\n\n\n:::\n\n```{.r .cell-code}\nn.grid     <- n.a:600\npower.grid <- sapply(n.grid, function(n)\n  PMCMRplus::power.tukey.test(n = n, groups = k.2, \n                              delta = delta.c, \n                              within.var = var.c)$power)\n\n(n.c <- n.grid[which(power.grid >= 0.80)[1]])   \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 315\n```\n\n\n:::\n\n```{.r .cell-code}\n(N.c <- n.c * k.2)                               \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1575\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(n = n.grid, power = power.grid) |>\n  ggplot(aes(x = n, y = power)) +\n  geom_line() +\n  geom_hline(yintercept = 0.80, linetype = \"dashed\") +\n  theme_bw() +\n  labs(x = \"Sample Size per Group (n)\", y = \"Power\",\n       title = \"Tukey Power for Stage 1 vs. Stage 2\")\n```\n\n::: {.cell-output-display}\n![](HW2_files/figure-html/q2c-plot-1.png){width=672}\n:::\n:::\n\n\n \\normalsize\n\nDetecting the specific difference between Stages 1 and 2 is harder for three reasons: the difference ($\\mu_\\Delta = 0.25$) is small relative to the within-group variability (about 0.28 standard deviations), a pairwise comparison uses information from only two groups, and Tukey's adjustment raises the critical value to control the family-wise error rate across all ten comparisons. With $n = 40$ per group, the power to detect the Stage 1 vs. Stage 2 difference is only 0.072. Achieving 80% power requires $n = 315$ per group ($N = 1575$). \n\n## Part d\nHow does the answer to Part c change if they wanted to have adequate power for *all* pairwise comparisons? Use `Superpower::ANOVA_design()` to set up the ANOVA set up.\n\n**Note**: Use design \"5b\" and the following.\n\\begin{align*}\n  \\boldsymbol{\\mu} &= \\{2.92, 3.11, 3.36, 4.04, 4.35\\}\\\\\n  \\sigma^2 &= \\frac{(97-1)0.87^2 + (176-1)0.85^2 + (135-1)0.84^2 + (67-1)1.00^2 + (67-1)0.90^2}{97+176+135+67+67-5} = 0.80\n\\end{align*}\n\nCompute the power of the researcher's design (part a) using `Superpower::ANOVA_power()`. If the researchers were able to oversample by double, a common approach to addressing this issue, would their power be at least 80% for all pariwise comparisons?\n\n**Note**: This code can take a minute. You may want to set `cache: true` in your `R` chunk yaml header. You will also see more power because the actual effect size was 0.55.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu.d  <- c(2.92, 3.11, 3.36, 4.04, 4.35)\nvar.d <- 0.80\n\ndesign.a <- Superpower::ANOVA_design(design = \"5b\",\n                                     n = n.a,\n                                     mu = mu.d,\n                                     sd = sqrt(var.d),\n                                     labelnames = c(\"Stage\", \"S0\", \"S1\", \n                                                    \"S2\", \"S3\", \"S4\"),\n                                     plot = TRUE)\n```\n\n::: {.cell-output-display}\n![](HW2_files/figure-html/q2d-design-1.png){width=672}\n:::\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Part a design: n = 40 per group\npower.d.a <- Superpower::ANOVA_power(design.a, nsims = 1000, \n                                     seed = 354, verbose = FALSE)\n\n# Doubled: n = 80 per group\ndesign.2a <- Superpower::ANOVA_design(design = \"5b\",\n                                      n = 2 * n.a,\n                                      mu = mu.d,\n                                      sd = sqrt(var.d),\n                                      labelnames = c(\"Stage\", \"S0\", \"S1\", \n                                                     \"S2\", \"S3\", \"S4\"),\n                                      plot = FALSE)\npower.d.2a <- Superpower::ANOVA_power(design.2a, nsims = 1000, \n                                      seed = 354, verbose = FALSE)\n```\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(power.d.table <- tibble(Comparison = rownames(power.d.a$pc_results),\n                         `n = 40`   = power.d.a$pc_results$power,\n                         `n = 80`   = power.d.2a$pc_results$power))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 3\n   Comparison          `n = 40` `n = 80`\n   <chr>                  <dbl>    <dbl>\n 1 p_Stage_S0_Stage_S1     13.9     28.8\n 2 p_Stage_S0_Stage_S2     57.5     88.8\n 3 p_Stage_S0_Stage_S3    100      100  \n 4 p_Stage_S0_Stage_S4    100      100  \n 5 p_Stage_S1_Stage_S2     24       41.7\n 6 p_Stage_S1_Stage_S3     99.3    100  \n 7 p_Stage_S1_Stage_S4    100      100  \n 8 p_Stage_S2_Stage_S3     91.7     99.9\n 9 p_Stage_S2_Stage_S4     99.8    100  \n10 p_Stage_S3_Stage_S4     35       59.1\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nUsing the Part a design ($n = 40$ per group), the power for each pairwise comparison ranges from 13.9% to 100%. The comparisons between widely separated stages (e.g., Stage 0 vs. Stage 4) have near-100% power, but four comparisons fall below 80%: Stage 0 vs. 1 (13.9%), Stage 0 vs. 2 (57.5%), Stage 1 vs. 2 (24.0%), and Stage 3 vs. 4 (35.0%). Doubling the sample size to $n = 80$ per group raises Stage 0 vs. 2 to 88.8%, but three comparisons remain underpowered: Stage 0 vs. 1 (28.8%), Stage 1 vs. 2 (41.7%), and Stage 3 vs. 4 (59.1%). So doubling the sample size would not give at least 80% power for all pairwise comparisons.\n\n# Question 3: An Application\n@Yang23 investigate whether low-dose nicotine can counteract age-related metabolic decline. The proposed mechanism is through $\\text{NAD}^+$, which is a chemical compound essential for metabolic energy production. The idea is that low-dose nicotine could help improve and/or maintain the recycling of $\\text{NAD}^+$ by activating the salvage enzyme NAMPT via SIRT1. This could, in turn, restore $\\text{NAD}^+$ homeostasis, which is the biological balance maintained within a cell between the production, recycling, and degradation of nicotinamide adenine dinucleotide ($\\text{NAD}^+$).\n\n**Note:** It is low-dose nicotine. Cigarette smoking delivers massive doses of nicotine along with other harmful chemicals. This is not an endorsement for smoking. \n\nMale mice across distinct life stages -- 2, 6, and 16 months -- were categorized to evaluate natural, age-dependent metabolic and enzymatic shifts in two conditions.\n\n* Treatment: low-dose nicotine (administered in drinking water)\n* Control: no-dose placebo (administered in drinking water)\n\nThe researchers then aimed to compare treatment against control in the following samples:\n\n* 2 months old, control\n* 6 months old, control\n* 16 months old, control\n* 16 months old, treatment\n\nUsing PET imaging, the researchers measured age-induced inflammatory glucose hypermetabolism ($\\text{SUV}_{\\text{max}}$). They want to show that this quantity increases with age and those in the nicotine group saw levels comparable to younger mice.\n\n| Replicate | 2M | 6M | 16M | 16M, Treatment |\n|:---|:---:|:---:|:---:|:---:|\n| 1 | 1.48969 | 4.36000 | 7.30182 | 4.69304 |\n| 2 | 1.30168 | 4.28807 | 7.12416 | 2.51326 |\n| 3 | 1.30620 | 3.64184 | 8.28764 | 2.38019 |\n\n: $\\text{SUV}_{\\text{max}}$ measurements in the heart across age and treatment groups {#tbl-SUV}\n\n## Part a\nState the null ($H_0$) and alternative ($H_a$) hypotheses for the omnibus test.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.q3 <- tibble(\n  Group = factor(rep(c(\"2M\", \"6M\", \"16M\", \"16M, Treatment\"), each = 3),\n                 levels = c(\"2M\", \"6M\", \"16M\", \"16M, Treatment\")),\n  SUV   = c(1.48969, 1.30168, 1.30620,    \n            4.36000, 4.28807, 3.64184,    \n            7.30182, 7.12416, 8.28764,    \n            4.69304, 2.51326, 2.38019))   \n```\n:::\n\n\n \\normalsize\n\nLet $\\mu_{2M}$, $\\mu_{6M}$, $\\mu_{16M}$, and $\\mu_{16M,T}$ denote the population mean $\\text{SUV}_{\\text{max}}$ for each group.\n\n$$H_0: \\mu_{2M} = \\mu_{6M} = \\mu_{16M} = \\mu_{16M,T}$$\n$$H_a: \\text{at least one population mean is different}$$\n\n## Part b\nPerform some exploratory data analysis to provide empirical information about the researchers question.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.q3 |>\n  group_by(Group) |>\n  summarize(n      = n(),\n            Mean   = mean(SUV),\n            Median = median(SUV),\n            SD     = sd(SUV),\n            IQR    = IQR(SUV))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 6\n  Group              n  Mean Median    SD    IQR\n  <fct>          <int> <dbl>  <dbl> <dbl>  <dbl>\n1 2M                 3  1.37   1.31 0.107 0.0940\n2 6M                 3  4.10   4.29 0.396 0.359 \n3 16M                3  7.57   7.30 0.627 0.582 \n4 16M, Treatment     3  3.20   2.51 1.30  1.16  \n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dat.q3, aes(x = Group, y = SUV)) +\n  geom_point(size = 2) +\n  stat_summary(fun = mean, geom = \"crossbar\", width = 0.4) +\n  theme_bw() +\n  labs(x = \"Group\", y = expression(SUV[max]))\n```\n\n::: {.cell-output-display}\n![](HW2_files/figure-html/q3-plot-1.png){width=672}\n:::\n:::\n\n\n \\normalsize\n\nThe control groups show a clear increase in $\\text{SUV}_{\\text{max}}$ with age, from a mean of about 1.37 at 2 months to 4.10 at 6 months and 7.57 at 16 months. The 16-month nicotine-treated mice had a mean of about 3.20, much lower than 16-month controls and between the 2- and 6-month controls, which is consistent with the researchers' hypothesis. However, the variability differs substantially across groups indicating we should be using Welch's ANOVA. \n\n## Part c\nPerform and report the results of the omnibus test. Make sure to evaluate the conditions for using the method you choose.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(test.result.q3 <- oneway.test(SUV ~ Group, data = dat.q3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne-way analysis of means (not assuming equal variances)\n\ndata:  SUV and Group\nF = 98.464, num df = 3.0000, denom df = 3.5496, p-value = 0.0006851\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nomega_squared(test.result.q3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Effect Size for ANOVA\n\nOmega2 |       95% CI\n---------------------\n0.97   | [0.83, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n\n```{.r .cell-code}\n(omega.q3 <- omega_squared(test.result.q3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Effect Size for ANOVA\n\nOmega2 |       95% CI\n---------------------\n0.97   | [0.83, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nWelch's ANOVA gives $F = 98.46$ with $3$ and $3.55$ degrees of freedom ($p = 6.85\\times 10^{-4}$). Since $p < \\alpha = 0.05$, the data provide statistically discernible support that the mean $\\text{SUV}_{\\text{max}}$ differs for at least one group. The effect size is very large ($\\omega^2 = 0.97$, 95% CI: [0.83, 1.00]), indicating that about 97% of the variability in $\\text{SUV}_{\\text{max}}$ is explained by differences between groups.\n\n## Part d\nConduct post-hoc pairwise comparisons to determine if age-induced inflammatory glucose hypermetabolism increase with age and whether low-dose nicotine reduces age-induced inflammatory glucose hypermetabolism. \n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(posthoc.result.q3 <- games_howell_test(SUV ~ Group, data = dat.q3) |>\n  mutate(Comparison = paste(group2, \"-\", group1)) |>\n  select(Comparison, estimate, conf.low, conf.high, p.adj))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  Comparison           estimate conf.low conf.high   p.adj\n  <chr>                   <dbl>    <dbl>     <dbl>   <dbl>\n1 6M - 2M                 2.73      1.31     4.15  0.0119 \n2 16M - 2M                6.21      3.81     8.60  0.00720\n3 16M, Treatment - 2M     1.83     -3.30     6.96  0.308  \n4 16M - 6M                3.47      1.56     5.39  0.00801\n5 16M, Treatment - 6M    -0.901    -5.47     3.67  0.698  \n6 16M, Treatment - 16M   -4.38     -8.51    -0.244 0.0431 \n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(posthoc.result.q3, aes(x = estimate, y = Comparison)) +\n  geom_vline(xintercept = 0, linetype = \"dashed\") +\n  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0.2) +\n  geom_point(size = 3) +\n  theme_bw() +\n  labs(x = \"Estimated Difference in Mean SUVmax\", y = \"\",\n       title = \"Games-Howell Pairwise Comparisons\")\n```\n\n::: {.cell-output-display}\n![](HW2_files/figure-html/q3-posthoc-plot-1.png){width=672}\n:::\n:::\n\n\n \\normalsize\n\n## Part e\nWrite a short paragraph directly addressing the researcher's hypothesis using your work in (a)-(d).\n\nThe data support the researchers' first claim and partially support the second. Welch's ANOVA provided statistically discernible support that mean $\\text{SUV}_{\\text{max}}$ differs across groups ($F = 98.46$, $p = 6.85\\times 10^{-4}$), with a very large effect size ($\\omega^2 = 0.97$). Games-Howell comparisons showed that $\\text{SUV}_{\\text{max}}$ increased significantly with age among control mice, from 2 to 6 months and from 6 to 16 months, so age-induced inflammatory glucose hypermetabolism does appear to increase with age. The 16-month nicotine-treated mice had lower $\\text{SUV}_{\\text{max}}$ than 16-month controls ($p = 0.043$), which suggests that low-dose nicotine reduces this age-related increase, although the evidence is borderline and the confidence interval is wide. However, the researchers only have three mice per group. Larger studies should be done to confirm the nicotine effect. \n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}